# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pjoyjr/csci300/SICXE-Assembler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pjoyjr/csci300/SICXE-Assembler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pjoyjr/csci300/SICXE-Assembler/CMakeFiles /home/pjoyjr/csci300/SICXE-Assembler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pjoyjr/csci300/SICXE-Assembler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SICXE-Assembler

# Build rule for target.
SICXE-Assembler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SICXE-Assembler
.PHONY : SICXE-Assembler

# fast build rule for target.
SICXE-Assembler/fast:
	$(MAKE) -f CMakeFiles/SICXE-Assembler.dir/build.make CMakeFiles/SICXE-Assembler.dir/build
.PHONY : SICXE-Assembler/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/SICXE-Assembler.dir/build.make CMakeFiles/SICXE-Assembler.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/SICXE-Assembler.dir/build.make CMakeFiles/SICXE-Assembler.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/SICXE-Assembler.dir/build.make CMakeFiles/SICXE-Assembler.dir/main.cpp.s
.PHONY : main.cpp.s

op_table.o: op_table.cpp.o
.PHONY : op_table.o

# target to build an object file
op_table.cpp.o:
	$(MAKE) -f CMakeFiles/SICXE-Assembler.dir/build.make CMakeFiles/SICXE-Assembler.dir/op_table.cpp.o
.PHONY : op_table.cpp.o

op_table.i: op_table.cpp.i
.PHONY : op_table.i

# target to preprocess a source file
op_table.cpp.i:
	$(MAKE) -f CMakeFiles/SICXE-Assembler.dir/build.make CMakeFiles/SICXE-Assembler.dir/op_table.cpp.i
.PHONY : op_table.cpp.i

op_table.s: op_table.cpp.s
.PHONY : op_table.s

# target to generate assembly for a file
op_table.cpp.s:
	$(MAKE) -f CMakeFiles/SICXE-Assembler.dir/build.make CMakeFiles/SICXE-Assembler.dir/op_table.cpp.s
.PHONY : op_table.cpp.s

sym_table.o: sym_table.cpp.o
.PHONY : sym_table.o

# target to build an object file
sym_table.cpp.o:
	$(MAKE) -f CMakeFiles/SICXE-Assembler.dir/build.make CMakeFiles/SICXE-Assembler.dir/sym_table.cpp.o
.PHONY : sym_table.cpp.o

sym_table.i: sym_table.cpp.i
.PHONY : sym_table.i

# target to preprocess a source file
sym_table.cpp.i:
	$(MAKE) -f CMakeFiles/SICXE-Assembler.dir/build.make CMakeFiles/SICXE-Assembler.dir/sym_table.cpp.i
.PHONY : sym_table.cpp.i

sym_table.s: sym_table.cpp.s
.PHONY : sym_table.s

# target to generate assembly for a file
sym_table.cpp.s:
	$(MAKE) -f CMakeFiles/SICXE-Assembler.dir/build.make CMakeFiles/SICXE-Assembler.dir/sym_table.cpp.s
.PHONY : sym_table.cpp.s

symbol.o: symbol.cpp.o
.PHONY : symbol.o

# target to build an object file
symbol.cpp.o:
	$(MAKE) -f CMakeFiles/SICXE-Assembler.dir/build.make CMakeFiles/SICXE-Assembler.dir/symbol.cpp.o
.PHONY : symbol.cpp.o

symbol.i: symbol.cpp.i
.PHONY : symbol.i

# target to preprocess a source file
symbol.cpp.i:
	$(MAKE) -f CMakeFiles/SICXE-Assembler.dir/build.make CMakeFiles/SICXE-Assembler.dir/symbol.cpp.i
.PHONY : symbol.cpp.i

symbol.s: symbol.cpp.s
.PHONY : symbol.s

# target to generate assembly for a file
symbol.cpp.s:
	$(MAKE) -f CMakeFiles/SICXE-Assembler.dir/build.make CMakeFiles/SICXE-Assembler.dir/symbol.cpp.s
.PHONY : symbol.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... SICXE-Assembler"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... op_table.o"
	@echo "... op_table.i"
	@echo "... op_table.s"
	@echo "... sym_table.o"
	@echo "... sym_table.i"
	@echo "... sym_table.s"
	@echo "... symbol.o"
	@echo "... symbol.i"
	@echo "... symbol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

